### ISSUE TITLE
lib not working with jest / jest regression

### ISSUE THREAD

**Issue by majirosstefan** [kpanuragh/zlib#4]
Using React Native v.64.1, and Jest ^26.6.3", it throws an error during running tests, 
probably because of Jest regression - more here: 
https://github.com/facebook/jest/issues/7780

This the stack of error:
```
TypeError: Not a string or buffer
        at zlibBufferSync (/Users/stefanmajiros/green-pass-reader/GreenPassIssuer/node_modules/react-zlib-js/index.js:1935:39)
        at Object.inflateSync (/Users/stefanmajiros/green-pass-reader/GreenPassIssuer/node_modules/react-zlib-js/index.js:1864:10)
        at decompressZlib (/Users/stefanmajiros/green-pass-reader/GreenPassIssuer/src/qrParser/zlibDecompressor.js:8:29)
```

If I comment this line  
`if (!Buffer.isBuffer(buffer)) throw new TypeError('Not a string or buffer');`
test pass.

**Comment by xhirazi** [comment]
@majirosstefan 
try using https://www.npmjs.com/package/rn-gzip

**Comment by kpanuragh** [comment]
Buffer in react-zlib-js not node native Buffer class its pure JS implementation of Buffer so You can't test buffer class with Node version of Buffer
